# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d938ba4dcfba9b3dba1f0833e0b590ce7721986bf29811715b1cf7341adc7aa3a995794ca2b564b7537a5b578808c7b991c2d696d13b320d87a0ce6686bc0b28

test:
  secret_key_base: 6ef596b5cdf317662a39df17a2834072eecb520da420f73d648e49e547eccd6e3abc1e6eea1005f8b897580098aee3b30c0bcca0810c7acc494762d67ce6bf18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
